import os
import logging
from fpdf import FPDF
from datetime import datetime
from telebot.domain.models import ChannelDigest

from fpdf.enums import XPos, YPos

logger = logging.getLogger(__name__)

class PDFRenderer:
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def render(self, digest: ChannelDigest, filename: str) -> str:
        """Render a ChannelDigest to a professional PDF report."""
        output_path = os.path.join(self.output_dir, filename)
        
        try:
            pdf = FPDF()
            pdf.add_page()
            
            # --- Header ---
            pdf.set_font("helvetica", "B", 24)
            pdf.set_text_color(44, 62, 80) # Dark Blue
            pdf.cell(0, 20, "Daily Digest", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
            
            pdf.set_font("helvetica", "B", 14)
            pdf.set_text_color(127, 140, 141) # Grey
            pdf.cell(0, 10, f"{digest.channel_name} - {digest.date}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
            pdf.ln(10)
            
            # --- Summaries ---
            pdf.set_font("helvetica", "B", 16)
            pdf.set_text_color(52, 152, 219) # Light Blue
            pdf.cell(0, 10, "Summary Highlights", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_draw_color(52, 152, 219)
            pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
            pdf.ln(5)
            
            pdf.set_font("helvetica", "", 11)
            pdf.set_text_color(44, 62, 80)
            for summary in digest.summaries:
                # Use multi_cell for wrapping text
                pdf.multi_cell(0, 7, f" {summary}")
                pdf.ln(2)
            
            # --- Action Items ---
            if digest.action_items:
                pdf.ln(5)
                pdf.set_font("helvetica", "B", 16)
                pdf.set_text_color(231, 76, 60) # Red
                pdf.cell(0, 10, "Action Items", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_draw_color(231, 76, 60)
                pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
                pdf.ln(5)
                
                pdf.set_font("helvetica", "", 11)
                pdf.set_text_color(44, 62, 80)
                for item in digest.action_items:
                    pdf.multi_cell(0, 7, f"[ ] {item}")
                    pdf.ln(1)

            # --- Key Links ---
            if digest.key_links:
                pdf.ln(5)
                pdf.set_font("helvetica", "B", 16)
                pdf.set_text_color(46, 204, 113) # Green
                pdf.cell(0, 10, "Key Resources & Links", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_draw_color(46, 204, 113)
                pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
                pdf.ln(5)
                
                pdf.set_font("helvetica", "", 10)
                pdf.set_text_color(41, 128, 185) # Link Blue
                for link in digest.key_links:
                    pdf.write(7, f" {link}", link=link)
                    pdf.ln(7)

            # --- Footer ---
            pdf.set_y(-20)
            pdf.set_font("helvetica", "I", 8)
            pdf.set_text_color(149, 165, 166)
            pdf.cell(0, 10, f"Generated by Telebot on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", align="C")

            pdf.output(output_path)
            return output_path
            
        except Exception as e:
            logger.error(f"Failed to generate PDF: {e}")
            return f"Error generating PDF: {str(e)}"
